In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
test = pd.read_csv('test.csv')

In [3]:
test_df = pd.DataFrame()
test_df['LotFrontage'] = test.LotFrontage.interpolate()

In [4]:
map_d = {'N': 0, 'Y': 1}
test_df['CentralAir'] = test.CentralAir.map(map_d)

In [5]:
columnas = ['LotArea', 'YearBuilt', 'GrLivArea', 'BedroomAbvGr', 'KitchenAbvGr', 'Fireplaces', 'GarageArea', 'OpenPorchSF']
for i in columnas:
    test_df[str(i)] = test[str(i)]

In [6]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1459 non-null   int64
 1   MSSubClass     1459 non-null   int64
 2   MSZoning       1455 non-null   object
 3   LotFrontage    1232 non-null   float64
 4   LotArea        1459 non-null   int64
 5   Street         1459 non-null   object
 6   Alley          107 non-null    object
 7   LotShape       1459 non-null   object
 8   LandContour    1459 non-null   object
 9   Utilities      1457 non-null   object
 10  LotConfig      1459 non-null   object
 11  LandSlope      1459 non-null   object
 12  Neighborhood   1459 non-null   object
 13  Condition1     1459 non-null   object
 14  Condition2     1459 non-null   object
 15  BldgType       1459 non-null   object
 16  HouseStyle     1459 non-null   object
 17  OverallQual    1459 non-null   int64
 18  OverallCond    1459 non-null   int64
 19  YearBuilt      1459 non-null   int64
 20  YearRemodAdd   1459 non-null   int64
 21  RoofStyle      1459 non-null   object
 22  RoofMatl       1459 non-null   object
 23  Exterior1st    1458 non-null   object
 24  Exterior2nd    1458 non-null   object
 25  MasVnrType     1443 non-null   object
 26  MasVnrArea     1444 non-null   float64
 27  ExterQual      1459 non-null   object
 28  ExterCond      1459 non-null   object
 29  Foundation     1459 non-null   object
 30  BsmtQual       1415 non-null   object
 31  BsmtCond       1414 non-null   object
 32  BsmtExposure   1415 non-null   object
 33  BsmtFinType1   1417 non-null   object
 34  BsmtFinSF1     1458 non-null   float64
 35  BsmtFinType2   1417 non-null   object
 36  BsmtFinSF2     1458 non-null   float64
 37  BsmtUnfSF      1458 non-null   float64
 38  TotalBsmtSF    1458 non-null   float64
 39  Heating        1459 non-null   object
 40  HeatingQC      1459 non-null   object
 41  CentralAir     1459 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1459 non-null   int64
 44  2ndFlrSF       1459 non-null   int64
 45  LowQualFinSF   1459 non-null   int64
 46  GrLivArea      1459 non-null   int64
 47  BsmtFullBath   1457 non-null   float64
 48  BsmtHalfBath   1457 non-null   float64
 49  FullBath       1459 non-null   int64
 50  HalfBath       1459 non-null   int64
 51  BedroomAbvGr   1459 non-null   int64
 52  KitchenAbvGr   1459 non-null   int64
 53  KitchenQual    1458 non-null   object
 54  TotRmsAbvGrd   1459 non-null   int64
 55  Functional     1457 non-null   object
 56  Fireplaces     1459 non-null   int64
 57  FireplaceQu    729 non-null    object
 58  GarageType     1383 non-null   object
 59  GarageYrBlt    1381 non-null   float64
 60  GarageFinish   1381 non-null   object
 61  GarageCars     1458 non-null   float64
 62  GarageArea     1458 non-null   float64
 63  GarageQual     1381 non-null   object
 64  GarageCond     1381 non-null   object
 65  PavedDrive     1459 non-null   object
 66  WoodDeckSF     1459 non-null   int64
 67  OpenPorchSF    1459 non-null   int64
 68  EnclosedPorch  1459 non-null   int64
 69  3SsnPorch      1459 non-null   int64
 70  ScreenPorch    1459 non-null   int64
 71  PoolArea       1459 non-null   int64
 72  PoolQC         3 non-null      object
 73  Fence          290 non-null    object
 74  MiscFeature    51 non-null     object
 75  MiscVal        1459 non-null   int64
 76  MoSold         1459 non-null   int64
 77  YrSold         1459 non-null   int64
 78  SaleType       1458 non-null   object
 79  SaleCondition  1459 non-null   object
dtypes: float64(11), int64(26), object(43)
memory usage: 912.0+ KB

In [7]:
test_df

,LotFrontage,CentralAir,LotArea,YearBuilt,GrLivArea,BedroomAbvGr,KitchenAbvGr,Fireplaces,GarageArea,OpenPorchSF
0,80.0,1,11622,1961,896,2,1,0,730.0,0
1,81.0,1,14267,1958,1329,3,1,0,312.0,36
2,74.0,1,13830,1997,1629,3,1,1,482.0,34
3,78.0,1,9978,1998,1604,3,1,1,470.0,36
4,43.0,1,5005,1992,1280,2,1,0,506.0,82
...,...,...,...,...,...,...,...,...,...,...
1454,21.0,1,1936,1970,1092,3,1,0,0.0,0
1455,21.0,1,1894,1970,1092,3,1,0,286.0,24
1456,160.0,1,20000,1960,1224,4,1,1,576.0,0
1457,62.0,1,10441,1992,970,3,1,0,0.0,32
1458,74.0,1,9627,1993,2000,3,1,1,650.0,48

In [8]:
test_df['Condition']= np.where(test['Condition1'] != test['Condition2'], 0, 1)

In [9]:
test_df['Mean_rank'] = (test.OverallQual + test.OverallCond) / 2

In [10]:
test_df['YearRemod'] = np.where(test['YearRemodAdd'] == test['YearBuilt'], 0, 1)
test_df['Exterior'] = np.where(test['Exterior1st'] == test['Exterior2nd'], 0, 1)
test_df['TotalSF'] = test['TotalBsmtSF'] + test['1stFlrSF'] + test['2ndFlrSF']

In [11]:
col = ['BsmtFullBath', 'BsmtHalfBath']

for i in col:
    test[str(i)]= test[str(i)].fillna(1)
test_df['TotalBath'] = test['BsmtFullBath'] + test['BsmtHalfBath']/2 + test['FullBath'] + test['HalfBath']/2

In [12]:
test_df['Age'] = test.YrSold - test.YearBuilt
test_df['WoodYN'] = np.where(test.WoodDeckSF > 0, 0, 1)
test_df.set_index(test.Id, inplace = True)

In [13]:
test_df

,LotFrontage,CentralAir,LotArea,YearBuilt,GrLivArea,BedroomAbvGr,KitchenAbvGr,Fireplaces,GarageArea,OpenPorchSF,Condition,Mean_rank,YearRemod,Exterior,TotalSF,TotalBath,Age,WoodYN
Id,,,,,,,,,,,,,,,,,,
1461,80.0,1,11622,1961,896,2,1,0,730.0,0,0,5.5,0,0,1778.0,1.0,49,0
1462,81.0,1,14267,1958,1329,3,1,0,312.0,36,1,6.0,0,0,2658.0,1.5,52,0
1463,74.0,1,13830,1997,1629,3,1,1,482.0,34,1,5.0,1,0,2557.0,2.5,13,0
1464,78.0,1,9978,1998,1604,3,1,1,470.0,36,1,6.0,0,0,2530.0,2.5,12,0
1465,43.0,1,5005,1992,1280,2,1,0,506.0,82,1,6.5,0,0,2560.0,2.0,18,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2915,21.0,1,1936,1970,1092,3,1,0,0.0,0,1,5.5,0,1,1638.0,1.5,36,1
2916,21.0,1,1894,1970,1092,3,1,0,286.0,24,1,4.5,0,1,1638.0,1.5,36,1
2917,160.0,1,20000,1960,1224,4,1,1,576.0,0,1,6.0,1,0,2448.0,2.0,46,0
2918,62.0,1,10441,1992,970,3,1,0,0.0,32,1,5.0,0,1,1882.0,1.5,14,0
2919,74.0,1,9627,1993,2000,3,1,1,650.0,48,1,6.0,1,0,2996.0,2.5,13,0

In [14]:
df = pd.read_csv('Train_data.csv').set_index('Id')
df.drop(['Unnamed: 0'], axis = 1, inplace=True)
df.shape

(1460, 19)

In [15]:
test_df.to_csv('Test_data.csv')
df.to_csv('Train_data.csv')